[package]
name = "stellar-horizon"
version = "0.6.0-beta.1"
authors = ["Francesco Ceccon <francesco@ceccon.me>"]
edition = "2018"
description = "Stellar Horizon client"
license = "Apache-2.0"
documentation = "https://docs.rs/stellar-horizon"
repository = "https://github.com/aurora-rs/stellar-horizon-rs"
readme = "README.md"
keywords = ["stellar", "blockchain"]

[dependencies]
stellar-base = "0.5.0-beta.1"
async-sse = "4.0.1"
base64 = "0.12.3"
chrono = { version = "0.4.13", features = ["serde"] }
eventsource = "0.5.0"
futures = "0.3.5"
hyper = "0.13.6"
hyper-tls = "0.4.1"
http = "0.2.1"
http-types = "2.2.1"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.56"
serde_with = { version = "1.5.0-alpha.1", features = ["default"] }
thiserror = "1.0.20"
url = "2.1.1"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["full"] }
json = "0.12.4"
hex = "0.4.2"