name: Deploy Docs
on:
  push:
    branches: [master]

jobs:
  ci:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --no-deps

      - name: Deploy GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_branch: gh-pages
            publish_dir: ./target/doc
            keep_files: true
